pipeline:
  build:
    image: ruby:2.2.4
    commands:
      - echo "Starting..."
      - ls 
      - pwd 
      - echo "Starting bundle"
      - gem install bundle 
      - bundle install
      - bundle exec rake assets:precompile
      