pipeline:
  build:
    image: glockio/rails-env
    commands:
      - echo "Starting..."
      - ls 
      - pwd 
      - echo "Starting bundle"
      - bundle install
      - bundle exec rake assests:precompile