pipeline:
  build:
    image: ruby:2.2.4
    commands:
      - echo " TODO -->  run tests here..."
  push: 
    image: glockio/release-env
    commands: 
      - git --version 
      - flynn --version 
      - echo $FLYNN_STAGING_CLUSTER_IP
      - echo $FLYNN_STAGING_CLUSTER_NAME
      - echo $FLYNN_STAGING_CONTROLLER_DOMAIN
      - echo $FLYNN_STAGING_CONTROLLER_KEY
    secrets: [
      flynn_staging_cluster_ip,
      flynn_staging_cluster_name,
      flynn_staging_controller_domain,
      flynn_staging_controller_key
    ]
      
      