# docker build -f ./Dockerfile . -t glockio/rails-env
pipeline:
  build:
    image: glockio/rails-env
    pull: true
    commands:
      - echo "Starting... with node..."
      - ls 
      - pwd 
      - echo "Starting bundle"
      - bundle install
      - bundle exec rake assests:precompile