pipeline:
  build:
    image: ruby:2.2.4
    commands:
      - echo " TODO -->  run tests here..."
  push: 
    image: glockio/release-env
    commands: 
      - git --version 
      - flynn --version 
      - echo $DOCKER_USERNAME
    secrets: [docker_username]

      